dist:
  xenial

language:
  python

python:
  3.7.2

install:
  ./.travis/install.sh

script:
  ./.travis/build.sh

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN

after_deploy:
  ./.travis/propagate.sh

notifications:
  slack:
    secure: rtZh7nl7+cxd/ITvCK/oTZ3KAIs6JoEZYqXgb7T943HlEQxL5lkA4m5SV4HlmsTlOJatg9HgTJg6KIhA0zdrWanVnQDcKNWYuSSIu4rcJiwFJqC1kaTs3dfjb8d4Cyzm8H4HV3L0pY0xeU0aHx/QAsjcYq5pnr5bbTB3oE1jk5wJXN7ZCQQYGO+ejRMCGbx0rDWLTOItA+NEcUZ2Pj1RJwb2aN5WK0GbhfowmK2210mITKx36d6pCPDWWU28AdhY83X1QdtrtvYZUf2+mwlqZhuwq/mH8zkf74IPxdZV9eb87bYFVYF1twLTnWL2/EX845/sCLIjKcJWCWwkptxQoQ9JZUKwtDhKA8cnzPPHukOAZwrvg1SQWa3Or/zG5utcjAEfM3BTu/qlsGilRSqJHFE15GFkZt7lTJlN2RLcfW/EV3boOZGl7ius4e01OR+V0uo8QFBnZag/MZVOeceS1b7ZxQMQLTTTB3wzuG2Wm10qZAkmpFZcvMsMUjJXnypToPAH7hC6ZJDoma5MC401RYAi1N04U+inkePU3mv/Rf2SAe1OGpHg1sPKWfazMMEt83k6OQFpdqzhjKi3U/5vmK+xzMbD2KsbeJb5H55HQtzRLhNvDyGCLRCmtYvkZsvA81Cm0aKrXwjb+6n3eNWI0wO9aBdPfv6W2Zjp08Wn3PY=
